#!/usr/bin/perl -w
## Coded by Douglas WeakNetLabs@Gmail.com
## For use with www.md5-lookup.com
## Don't abuse these websites! Please!!
##
## Need CURL, GREP AND SED

$hash = 0;
use Term::ANSIColor;
use LWP::UserAgent;
use LWP::Simple;

if ($ARGV[0] eq '') { print STDERR "Usage: ./md5online <word>\n"; exit(); }
if ($ARGV[0] =~ m/[A-Fa-f0-9\/_.-]{32}/) {
	explain();
	print "Performing reverse hash lookup. \n";
	$hash = 1;
}
$regexp0 = '<\(\/\)\?td>';
$regexp1 = '\s';
if ($hash == 0) {
	$md5 = `curl http://www.md5-lookup.com/index.php?q=$ARGV[0] 2>/dev/null | grep -m 1 -i -E '[0-9a-f]{32}' | sed -e 's/$regexp0//g' -e 's/$regexp1//g'`;
	chomp($md5);
}else{ 
	@md5 = `curl http://www.md5-lookup.com/index.php?q=$ARGV[0] 2>/dev/null`;
	for($h=0;$h<=$#md5;$h++) {
		if ($md5[$h] =~ m/[A-Fa-f0-9]{32}/) {
			$md5 = $md5[$h - 1];
			$md5 =~ s/<td width="[0-9]+">//g;
			$md5 =~ s/<\/td>//g;
			$md5 =~ s/\s//g;
		}
	}
}
if ($md5) { # Nice and easy now, let's land properly on the runway. 
	explain();
	if ($hash == 0) {
		print "MD5 Hash for ";
	}else{
		print "Passwd for hash: ";
	}
	print color 'bold blue'; 
	print $ARGV[0];
	print color 'reset';
	print" is ";
	print color 'bold blue';
	print $md5 . "\n"; 
	print color 'reset';
} else { passcrack($ARGV[0]); } # is this appppropiate? I am soo drud ,d drinju drunk.


sub passcrack {
	explain();
	print "Trying another resource.\n";
	$ua = new LWP::UserAgent;
	$ua->agent("AgentName/0.1 " . $ua->agent);
	
	my $req = new HTTP::Request POST => 'http://passcracking.com/index.php';
	$req->content_type('application/x-www-form-urlencoded');
	$req->content('datafromuser=' . $_[0]);
	my $res = $ua->request($req);
	
	if ($res->is_success) {
	        # sed 's/<[^>]*>//g' | awk '{print $2}' | sed 's/^Database//'
	        $output = $res->content;
	        $output =~ s/<[^>]*>/ /g;
	        @splt = split(/\s/, $output);
		$n = 0; # <-- I know, I knwo, I am jdust drunks right nwow,,
	        foreach (@splt) {
	                if ($_ =~ m/^Data/) {
	                        $password = $splt[$n + 4];
				explain();
	                        print "Passwd Found: ";
	                        print color 'bold red';
	                        print $password . "\n";
	                        print color 'reset';
	                }
			$n++;
		}
	        if (!$password) {
			explain();
			print "Trying yet another resource.\n";
			hashcracking($_[0]);
	        }
	}else{
		explain();
	        print "This site seems to be down!\n";
	}
}
sub explain {
	print color 'bold red';
        print "[ ";
        print color 'bold yellow';
        print "!";
        print color 'bold red';
        print " ] ";
        print color 'reset';
}
sub hashcracking {
	$md5 = `curl http://md5.hashcracking.com/search.php?md5=$_[0] 2>/dev/null`;
	if ($md5 ne '') {
		explain();
		chomp ($md5);
		print $md5 . "\n";
	}
	if ($md5 =~ m/No results returned./) {
		hashcracker($_[0]);
	}
}
sub hashcracker {
	explain();
	print "Using ";
	print color 'bold blue';
	print "G";
	print color 'bold red';
	print "o";
	print color 'bold yellow';
	print "o";
	print color 'bold blue';
	print "g";
	print color 'bold green';
	print "l";
	print color 'bold red';
	print "e";
	print color 'reset';
	print " as a last resort.\n";
	$ua = new LWP::UserAgent;
	$ua->agent("AgentName/0.1 " . $ua->agent);
	
	my $req = new HTTP::Request POST => 'http://md5crack.com/crackmd5.php';
	$req->content_type('application/x-www-form-urlencoded');
	$req->content('term=' . $_[0]);
	
	my $res = $ua->request($req);
	
	if ($res->is_success) {
	        @splt = split(/\s/, $res->content);
	        for ($i=0;$i<$#splt;$i++) {
	                if ($splt[$i] =~ m/Found:/) {
	                        $md5 = $splt[$i + 1];
	                        $md5 =~ s/md5\("//;
	                        $md5 =~ s/"\)//;
				explain();
	                        print "Passwd Found: ";
				print color 'bold green';
				print $md5;
				print color 'reset';
				print " :D\n";
	                }
	        }
	        if (!$md5) {
			explain();
	                print "Password cannot be recovered using this resource\n";
	        }
	}else{
	        print "Site is down :-(";
	}

}
exit();
