#!/usr/bin/perl -w
use Term::ANSIColor;
print color 'bold yellow';
@date = localtime;
print "\npBinCracker";
print color 'reset';
print " - pasteBin and Paste2 RAW MD5 cracking software\nLogs all results to pCrack Suite's log directory.\n";
print "" . ($date[5] + 1900) . " (c) - WeakNetLabs.com\n\n";
if(!$ARGV[0]) { 
	print "Usage: ./pBincracker <URL>\nMust contain raw MD5 hashes.\n\n";
	exit();
}else{
	$logDir = $ARGV[0];
	$logDir =~ s/.*com/..\/logs\/pBin/;
	$logDir .= ".txt";
	open(LOG, ">$logDir");
	print LOG "Log file created by pBincracker\n" . ($date[5] + 1900) . " (c) - WeakNetLabs.com\n\n$ARGV[0]\n\n";
}
@md5s = `curl $ARGV[0] 2>/dev/null`;
@md5History = ();
foreach (@md5s) { 
	$_ =~ s/<[^>]*>//g;
	@colons = split(/:/, $_);
	foreach (@colons) {
		@removespace = split(/\s+/, $_);
		foreach (@removespace) {
			if ($_ =~ m/[a-f0-9]{32}/i) {
				$_ =~ s/&nbsp;//g;
				my $hash = $_;
				if(grep(/$hash/, @md5History)) { print "[ X ] Already tried " . $_ . "\n"; next(); }
				push(@md5History, $_);
				# foreach $md5his (@md5History) { print "[ DBG ]: " . $md5his . "\n"; }
				print "[ ! ] Testing hash " . $_ . "\n";
				@check = `./md5online $_`;
				if(grep(/Found/, @check)) { 
					print LOG "\n[ HASH ]: " . $_ . "\n";
					print "[ HASH ]: " . $_ . "\n";
					foreach $hashline (@check) {
						print $hashline; 
						print LOG $hashline;
						print "\n";
					}
				}else{
					print "[ X ] password not recovered\n";
				}
			}	
		}
	}
}
close LOG;
